name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPOSITORY: wxxxcxx/naive
  AARCH: linux-x64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        run: echo VERSION=$(wget -qO- -t1 -T2 "https://api.github.com/repos/klzgrad/naiveproxy/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g') >> $GITHUB_ENV
      
      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          build-args: |
            VERSION: ${{ env.VERSION }}
            AARCH: $${{ env.AARCH }}
          platforms: |
            linux/amd64
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:${{ env.VERSION }}-${{ env.AARCH }}
            ${{ env.DOCKER_REPOSITORY }}:latest